# Configuration script to Travis-CI
language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - pypy-5.4.1
    - pypy3.3-5.2-alpha1
matrix:
    include:
        - python: "2.7"
          env: TOXENV=flake8,docs
install:
    - pip install tox tox-travis
script:
    - tox
# Alternative: use buildout instead of tox
#install:
#    - python bootstrap.py
#    - bin/buildout
#script:
#    - bin/test -v1
notifications:
    email: false
